name: Update Repo Manifest

on:
  push:
    branches:
      - main

jobs:
  update-manifest:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up PowerShell
      shell: pwsh
      run: |
        # Just a sanity check to see PowerShell version
        $PSVersionTable.PSVersion

    - name: Generate manifest
      shell: pwsh
      run: |
        ./generate_manifest.ps1

    - name: Commit and push manifest
      shell: pwsh
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add repo_manifest.json
        git commit -m "Update repo_manifest.json [CI skip]" || echo "No changes to commit"
        git push
